epr_app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :products
  resources :iphones
  resources :smarts
  resources :tablets
  resources :users
  resources :sessions
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

epr_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

epr_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	private
	def current_user
		@current_user ||=User.find(session[ :user_id]) if session[ :user_id]
	end
	helper_method :current_user
	def authorize
		redirect_to new_session_path, alert: 'Plesae Log in or Sign Up' if current_user.nil?
	end
end

epr_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

epr_app/app/helpers/application_helper.rb
module ApplicationHelper
end

epr_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

epr_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EprApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

      <h5 class="my-0 mr-md-auto font-weight-normal"> EPR </h5>

      <nav class="my-2 my-md-0 mr-md-3">


        <a class="p-2 text-dark" href="#"><%= link_to "Home", static_pages_home_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "About Us", static_pages_about_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Contact Us", static_pages_contact_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Products", products_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Iphone", iphones_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Smart TV", smarts_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Tablet", tablets_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Create Account", new_user_path %></a>
        <a class="p-2 text-dark" href="#"><%= link_to "Profiles", profiles_path %></a>
        <% if current_user %>
        <a class="p-2 text-dark" href="#">
        <%= link_to 'Log out', session_path('active'), method:
:delete %>
 </a>
 <a class="p-2 text-dark" href="#">
 <%= current_user.userid %>
 </a>
 <% else %>
<a class="p-2 text-dark" href="#">
<%= link_to 'Log in', new_session_path, class: "active_nav_link" %>
 </a>
 <% end %>

    
       
      </nav>

      

    </div>
</div>

  <div class="container">
    <% if alert %>
    <%= alert %>
    <% end %>

    <% if notice %>
    <%= notice %>
    <% end %>

    <%= yield %>
  </div>

  </body>

</html>

epr_app/app/views/static_pages/about.html.erb
<div class="container">
	<h1 class="jumbotrol-heading">About Us</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p><h4> Who are we? </h4> We are Electronic Product Reviews </p>
			</div>
			<div class="col">
				<p><h4> What we do</h4> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est placerat in egestas erat imperdiet sed euismod nisi porta.</p>
			</div>
			<div class="col">
				<p><h4> Why we do it</h4> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est placerat in egestas erat imperdiet sed euismod nisi porta.</p>
			</div>
			<div class="col">
				<p><h4> Location </h4> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est placerat in egestas erat imperdiet sed euismod nisi porta.</p>
			</div>
		</div>
	</div>

epr_app/app/views/static_pages/contact.html.erb
<div class="container">
	<h1 class="jumbotrol-heading">Contact Us</h1>
<div id="after_submit"></div>
<form id="contact_form" action="#" method="POST" enctype="multipart/form-data">
  <div class="row">
    <label class="required" for="name">Your name: </label><br />
    <input id="name" class="input" name="name" type="text" value="" size="30" /><br />
    <span id="name_validation" class="error_message"></span>
  </div>
  <div class="row">
    <label class="required" for="email">Your email: </label><br />
    <input id="email" class="input" name="email" type="text" value="" size="30" /><br />
    <span id="email_validation" class="error_message"></span>
  </div>
  <div class="row">
    <label class="required" for="message">Your message: </label><br />
    <textarea id="message" class="input" name="message" rows="7" cols="30"></textarea><br />
    <span id="message_validation" class="error_message"></span>
  </div>
    
    <input id="submit_button" type="submit" value="Send email" />
</form>
</div>

epr_app/app/views/static_pages/home.html.erb
<div class="container">
	<h1 class="jumbotrol-heading">Welcome to EPR Home</h1>
	<div class="container">
		<div class="row">
			<div class="col">
				<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel turpis nunc eget lorem dolor sed viverra ipsum. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Rhoncus aenean vel elit scelerisque mauris pellentesque. Eget dolor morbi non arcu risus quis varius quam quisque. </p>
			</div>
			<div class="col">
				<p><%= image_tag "iphone.jpg", size: "250x250" %></p>
			</div>
			<div class="col">
				<p><%= image_tag "tv.jpg", size: "350x250" %></p>
			</div>
			<div class="col">
				<p><%= image_tag "ipad.jpg", size: "350x250" %></p>
			</div>
		</div>
	</div>